name: HealPlugin
version: 1.0
main: com.JavaBeast.healPlugin.Main
author: JavaBeast
website: javabeast.bplaced.net
database: false
description: tool to heal you and your friends

commands:
  heal:
    permission: heal.command.heal